baseURL = 'https://chaploud.github.io/blog/'
languageCode = 'ja'
title = 'chaploud dev notes'
theme = 'PaperMod'

[params]
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
mainSections = ["posts"]

[markup]
[markup.highlight]
style = "tokyonight-night"

# [menu]
# [[menu.main]]
# name = "About"
# url = "/pages/about/"
# weight = 30
