baseURL = 'https://chaploud.github.io/blog/'
languageCode = 'ja'
title = 'My Blog'
theme = 'PaperMod'

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
