baseURL = 'https://chaploud.github.io/blog/'
languageCode = 'ja'
title = 'chaploud dev notes'
theme = 'PaperMod'

[params]
ShowReadingTime = false
ShowShareButtons = true
ShowPostNavLinks = false
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
mainSections = ["posts"]
ShareButtons = ["x", "linkedin", "clipboard"]
[params.cover]
image = "images/scilisp.png"

[markup]
[markup.highlight]
style = "tokyonight-night"

[menu]
[[menu.main]]
name = "ポスト一覧"
url = "/posts/"
weight = 30
[[menu.main]]
name = "ページ一覧"
url = "/pages/"
weight = 40
[[menu.main]]
name = "AI生成ページ一覧"
url = "/ai-generated/"
weight = 50
[[menu.main]]
name = "リンク集"
url = "/links/"
weight = 60
